(ns netwars.tiles
  (:use [netwars.aw-map :only [coord]]))

;; (defn- make-tiling-spec [directory]
;;   (let [files (filter #(.isFile %) (file-seq (java.io.File. directory)))]
;;     (for [file files]
;;       (let [key (-> file
;;                     (.getPath)
;;                     (.substring (count directory))
;;                     (.split (java.util.regex.Pattern/quote java.io.File/separator))
;;                     vec
;;                     ;; (update-in [1] #(.substring % 0 (- (count %) 4)))
;;                     )]
;;        [(vec (map keyword key)) file]))))

;; (defn- make-tile [spec]
;;   (let [image (BufferedImage. (* 16 (count spec)) 16 BufferedImage/TYPE_INT_ARGB)
;;         graphics (.createGraphics image)
;;         tile-coords (for [x (range (count spec))
;;                           :let [[key file] (nth spec x)]]
;;                       (do (.drawImage graphics (ImageIO/read file)
;;                                       (* x 16) 0
;;                                       nil)
;;                           [key (coord (* x 16) 0)]))]

;;     (.finalize graphics)
;;     [(into {} tile-coords) image]))

;; (defn- load-tile [directory]
;;   (-> directory
;;       make-tiling-spec
;;       make-tile))

;; (load-tile "resources/pixmaps/units/")

;; (into {} (for [[k {:keys [x y]}] (first (load-tile "resources/pixmaps/units/"))] [k (list 'coord x y)]))

;; (pprint (into {} (for [[k {:keys [x y]}] (first (load-tile "resources/pixmaps/units/"))] [k (list 'coord x y)])))
;; (javax.imageio.ImageIO/write (second (load-tile "resources/pixmaps/units/")) "png" (java.io.File. "/Users/moritz/units.png"))

(defrecord TileRect [x y width height])

(defn coord->TileRect
  ([c width height]
     (TileRect. (:x c) (:y c) width height))
  ([c] (coord->TileRect c 0 0)))

(defn origin [ta]
  (coord (:x ta) (:y ta)))

(defn tile-filename [tile]
  (:tile-filename tile))

;;; TODO: Find a better way to do this in ClojureScript

;; (require '[clojure.java.io :as io])
;; (import 'java.awt.image.BufferedImage
;;         'java.awt.Graphics2D
;;         'javax.imageio.ImageIO)
;; (defn tile-path [tile]
;;   (-> tile :tile-path io/resource io/file))
;; (defn tile-image [tile]
;;   (ImageIO/read (tile-path tile)))

(defn tile-rect [tile path]
  (when-let [c (get-in tile [:tile-spec (vec path)])]
    (let [[width height] (:tile-size tile)]
      (coord->TileRect c width height))))

(def +unit-meta-tiles+
  {:tile-filename "unit-meta.png"
   :tile-size [16 16]
   :tile-spec {[:ammo]    (coord 0 0)
               [:capture] (coord 16 0)
               [:eight]   (coord 32 0)
               [:five]    (coord 48 0)
               [:four]    (coord 64 0)
               [:fuel]    (coord 80 0)
               [:hidden]  (coord 96 0)
               [:loaded]  (coord 112 0)
               [:nine]    (coord 144 0)
               [:one]     (coord 160 0)
               [:seven]   (coord 176 0)
               [:six]     (coord 192 0)
               [:three]   (coord 208 0)
               [:two]     (coord 224 0)
               [:minus]   (coord 128 0)}})

(def +unit-tiles+
  {:tile-filename "units.png"
   :tile-size [16 16]
   :tile-spec {[:black :anti-air]    (coord 16 0)
               [:black :apc]         (coord 32 0)
               [:black :artillery]   (coord 48 0)
               [:black :b-boat]      (coord 64 0)
               [:black :b-bomb]      (coord 80 0)
               [:black :b-copter]    (coord 96 0)
               [:black :battleship]  (coord 112 0)
               [:black :bomber]      (coord 128 0)
               [:black :carrier]     (coord 144 0)
               [:black :cruiser]     (coord 160 0)
               [:black :fighter]     (coord 176 0)
               [:black :infantry]    (coord 192 0)
               [:black :lander]      (coord 208 0)
               [:black :md-tank]     (coord 224 0)
               [:black :mech]        (coord 240 0)
               [:black :megatank]    (coord 256 0)
               [:black :missiles]    (coord 272 0)
               [:black :neotank]     (coord 288 0)
               [:black :oozium]      (coord 304 0)
               [:black :piperunner]  (coord 320 0)
               [:black :recon]       (coord 336 0)
               [:black :rockets]     (coord 352 0)
               [:black :stealth]     (coord 368 0)
               [:black :submarine]   (coord 384 0)
               [:black :t-copter]    (coord 400 0)
               [:black :tank]        (coord 416 0)
               [:blue :anti-air]     (coord 432 0)
               [:blue :apc]          (coord 448 0)
               [:blue :artillery]    (coord 464 0)
               [:blue :b-boat]       (coord 480 0)
               [:blue :b-bomb]       (coord 496 0)
               [:blue :b-copter]     (coord 512 0)
               [:blue :battleship]   (coord 528 0)
               [:blue :bomber]       (coord 544 0)
               [:blue :carrier]      (coord 560 0)
               [:blue :cruiser]      (coord 576 0)
               [:blue :fighter]      (coord 592 0)
               [:blue :infantry]     (coord 608 0)
               [:blue :lander]       (coord 624 0)
               [:blue :md-tank]      (coord 640 0)
               [:blue :mech]         (coord 656 0)
               [:blue :megatank]     (coord 672 0)
               [:blue :missiles]     (coord 688 0)
               [:blue :neotank]      (coord 704 0)
               [:blue :oozium]       (coord 720 0)
               [:blue :piperunner]   (coord 736 0)
               [:blue :recon]        (coord 752 0)
               [:blue :rockets]      (coord 768 0)
               [:blue :stealth]      (coord 784 0)
               [:blue :submarine]    (coord 800 0)
               [:blue :t-copter]     (coord 816 0)
               [:blue :tank]         (coord 832 0)
               [:green :anti-air]    (coord 848 0)
               [:green :apc]         (coord 864 0)
               [:green :artillery]   (coord 880 0)
               [:green :b-boat]      (coord 896 0)
               [:green :b-bomb]      (coord 912 0)
               [:green :b-copter]    (coord 928 0)
               [:green :battleship]  (coord 944 0)
               [:green :bomber]      (coord 960 0)
               [:green :carrier]     (coord 976 0)
               [:green :cruiser]     (coord 992 0)
               [:green :fighter]     (coord 1008 0)
               [:green :infantry]    (coord 1024 0)
               [:green :lander]      (coord 1040 0)
               [:green :md-tank]     (coord 1056 0)
               [:green :mech]        (coord 1072 0)
               [:green :megatank]    (coord 1088 0)
               [:green :missiles]    (coord 1104 0)
               [:green :neotank]     (coord 1120 0)
               [:green :oozium]      (coord 1136 0)
               [:green :piperunner]  (coord 1152 0)
               [:green :recon]       (coord 1168 0)
               [:green :rockets]     (coord 1184 0)
               [:green :stealth]     (coord 1200 0)
               [:green :submarine]   (coord 1216 0)
               [:green :t-copter]    (coord 1232 0)
               [:green :tank]        (coord 1248 0)
               [:red :anti-air]      (coord 1264 0)
               [:red :apc]           (coord 1280 0)
               [:red :artillery]     (coord 1296 0)
               [:red :b-boat]        (coord 1312 0)
               [:red :b-bomb]        (coord 1328 0)
               [:red :b-copter]      (coord 1344 0)
               [:red :bomber]        (coord 1376 0)
               [:red :carrier]       (coord 1392 0)
               [:red :cruiser]       (coord 1408 0)
               [:red :fighter]       (coord 1424 0)
               [:red :infantry]      (coord 1440 0)
               [:red :lander]        (coord 1456 0)
               [:red :md-tank]       (coord 1472 0)
               [:red :mech]          (coord 1488 0)
               [:red :megatank]      (coord 1504 0)
               [:red :missiles]      (coord 1520 0)
               [:red :neotank]       (coord 1536 0)
               [:red :oozium]        (coord 1552 0)
               [:red :piperunner]    (coord 1568 0)
               [:red :recon]         (coord 1584 0)
               [:red :rockets]       (coord 1600 0)
               [:red :stealth]       (coord 1616 0)
               [:red :submarine]     (coord 1632 0)
               [:red :t-copter]      (coord 1648 0)
               [:red :tank]          (coord 1664 0)
               [:yellow :anti-air]   (coord 1680 0)
               [:yellow :apc]        (coord 1696 0)
               [:yellow :artillery]  (coord 1712 0)
               [:yellow :b-boat]     (coord 1728 0)
               [:yellow :b-bomb]     (coord 1744 0)
               [:yellow :b-copter]   (coord 1760 0)
               [:yellow :battleship] (coord 1776 0)
               [:yellow :bomber]     (coord 1792 0)
               [:yellow :carrier]    (coord 1808 0)
               [:yellow :cruiser]    (coord 1824 0)
               [:yellow :fighter]    (coord 1840 0)
               [:yellow :infantry]   (coord 1856 0)
               [:yellow :lander]     (coord 1872 0)
               [:yellow :md-tank]    (coord 1888 0)
               [:yellow :mech]       (coord 1904 0)
               [:yellow :megatank]   (coord 1920 0)
               [:yellow :missiles]   (coord 1936 0)
               [:yellow :neotank]    (coord 1952 0)
               [:yellow :oozium]     (coord 1968 0)
               [:yellow :piperunner] (coord 1984 0)
               [:yellow :recon]      (coord 2000 0)
               [:yellow :rockets]    (coord 2016 0)
               [:yellow :stealth]    (coord 2032 0)
               [:yellow :submarine]  (coord 2048 0)
               [:yellow :t-copter]   (coord 2064 0)
               [:yellow :tank]       (coord 2080 0)
               [:red :battleship]    (coord 1360 0)}})


;; (pprint (into {} (for [[k {:keys [x y]}] (first (load-tile "resources/pixmaps/units/"))] [k (list 'coord x y)])))
;; (javax.imageio.ImageIO/write (second (load-tile "resources/pixmaps/units/")) "png" (java.io.File. "/Users/moritz/units.png"))

(def +terrain-tiles+
  {:tile-filename "terrain.png"
   :tile-size [16 16]
   :tile-spec {[:beach :d]                       (coord 0 0)
               [:beach :dr]                      (coord 16 0)
               [:beach :l]                       (coord 32 0)
               [:beach :ld]                      (coord 48 0)
               [:beach :ldr]                     (coord 64 0)
               [:beach :r]                       (coord 80 0)
               [:beach :u]                       (coord 96 0)
               [:beach :udr]                     (coord 112 0)
               [:beach :ul]                      (coord 128 0)
               [:beach :uld]                     (coord 144 0)
               [:beach :ulr]                     (coord 160 0)
               [:beach :ur]                      (coord 176 0)
               [:bridge :lr]                     (coord 192 0)
               [:bridge :ud]                     (coord 208 0)
               [:buildings :airport :black]      (coord 240 0)
               [:buildings :airport :blue]       (coord 256 0)
               [:buildings :airport :green]      (coord 272 0)
               [:buildings :airport :red]        (coord 288 0)
               [:buildings :airport :white]      (coord 304 0)
               [:buildings :airport :yellow]     (coord 320 0)
               [:buildings :base :black]         (coord 336 0)
               [:buildings :base :blue]          (coord 352 0)
               [:buildings :base :green]         (coord 368 0)
               [:buildings :base :red]           (coord 384 0)
               [:buildings :base :white]         (coord 400 0)
               [:buildings :base :yellow]        (coord 416 0)
               [:buildings :city :black]         (coord 432 0)
               [:buildings :city :blue]          (coord 448 0)
               [:buildings :city :green]         (coord 464 0)
               [:buildings :city :red]           (coord 480 0)
               [:buildings :city :white]         (coord 496 0)
               [:buildings :city :yellow]        (coord 512 0)
               [:buildings :headquarter :black]  (coord 544 0)
               [:buildings :headquarter :blue]   (coord 560 0)
               [:buildings :headquarter :green]  (coord 576 0)
               [:buildings :headquarter :red]    (coord 592 0)
               [:buildings :headquarter :yellow] (coord 608 0)
               [:buildings :lab :black]          (coord 624 0)
               [:buildings :lab :blue]           (coord 640 0)
               [:buildings :lab :green]          (coord 656 0)
               [:buildings :lab :red]            (coord 672 0)
               [:buildings :lab :white]          (coord 688 0)
               [:buildings :lab :yellow]         (coord 704 0)
               [:buildings :port :black]         (coord 720 0)
               [:buildings :port :blue]          (coord 736 0)
               [:buildings :port :green]         (coord 752 0)
               [:buildings :port :red]           (coord 768 0)
               [:buildings :port :white]         (coord 784 0)
               [:buildings :port :yellow]        (coord 800 0)
               [:buildings :silo :white]         (coord 816 0)
               [:buildings :silo :white_shot]    (coord 832 0)
               [:buildings :tower :black]        (coord 848 0)
               [:buildings :tower :blue]         (coord 864 0)
               [:buildings :tower :green]        (coord 880 0)
               [:buildings :tower :red]          (coord 896 0)
               [:buildings :tower :white]        (coord 912 0)
               [:buildings :tower :yellow]       (coord 928 0)
               [:forest]                         (coord 944 0)
               [:mountain :big]                  (coord 960 0)
               [:mountain :small]                (coord 976 0)
               [:pipe :d]                        (coord 992 0)
               [:pipe :dr]                       (coord 1008 0)
               [:pipe :l]                        (coord 1024 0)
               [:pipe :ld]                       (coord 1040 0)
               [:pipe :lr]                       (coord 1056 0)
               [:pipe :r]                        (coord 1072 0)
               [:pipe :u]                        (coord 1088 0)
               [:pipe :ud]                       (coord 1104 0)
               [:pipe :ul]                       (coord 1120 0)
               [:pipe :ur]                       (coord 1136 0)
               [:plain]                          (coord 1152 0)
               [:reef]                           (coord 1168 0)
               [:river :dr]                      (coord 1184 0)
               [:river :ld]                      (coord 1200 0)
               [:river :ldr]                     (coord 1216 0)
               [:river :lr]                      (coord 1232 0)
               [:river :mouth :d]                (coord 1248 0)
               [:river :mouth :l]                (coord 1264 0)
               [:river :mouth :r]                (coord 1280 0)
               [:river :mouth :u]                (coord 1296 0)
               [:river :ud]                      (coord 1312 0)
               [:river :udr]                     (coord 1328 0)
               [:river :ul]                      (coord 1344 0)
               [:river :uld]                     (coord 1360 0)
               [:river :uldr]                    (coord 1376 0)
               [:river :ulr]                     (coord 1392 0)
               [:river :ur]                      (coord 1408 0)
               [:seaside :corner :dr]            (coord 1424 0)
               [:seaside :corner :ld]            (coord 1440 0)
               [:seaside :corner :ul]            (coord 1456 0)
               [:seaside :corner :ur]            (coord 1472 0)
               [:seaside :d]                     (coord 1488 0)
               [:seaside :dr]                    (coord 1504 0)
               [:seaside :l]                     (coord 1520 0)
               [:seaside :ld]                    (coord 1536 0)
               [:seaside :ldr]                   (coord 1552 0)
               [:seaside :lr]                    (coord 1568 0)
               [:seaside :r]                     (coord 1584 0)
               [:seaside :u]                     (coord 1600 0)
               [:seaside :ud]                    (coord 1616 0)
               [:seaside :udr]                   (coord 1632 0)
               [:seaside :ul]                    (coord 1648 0)
               [:seaside :uld]                   (coord 1664 0)
               [:seaside :uldr]                  (coord 1680 0)
               [:seaside :ulr]                   (coord 1696 0)
               [:seaside :ur]                    (coord 1712 0)
               [:segment-pipe :lr]               (coord 1728 0)
               [:segment-pipe :ud]               (coord 1744 0)
               [:street :dr]                     (coord 1760 0)
               [:street :ld]                     (coord 1776 0)
               [:street :ldr]                    (coord 1792 0)
               [:street :lr]                     (coord 1808 0)
               [:street :ud]                     (coord 1824 0)
               [:street :udr]                    (coord 1840 0)
               [:street :ul]                     (coord 1856 0)
               [:street :uld]                    (coord 1872 0)
               [:street :uldr]                   (coord 1888 0)
               [:street :ulr]                    (coord 1904 0)
               [:street :ur]                     (coord 1920 0)
               [:water]                          (coord 1936 0)
               [:wreckage :lr]                   (coord 1952 0)
               [:wreckage :ud]                   (coord 1968 0)
               [:wreckage]                       (coord 1984 0)}})
